"""
Trains the tiny sketch classifier on data/quickdraw/*.bin (built by scripts/quickdraw/prepare.mts)
and exports int8-quantised weights to shared/sketch/model.gen.ts for the dependency-free
TypeScript inference in shared/sketch/net.ts. Also writes parity samples so the TS port can be
checked against PyTorch (data/quickdraw/parity.json).
"""
import base64, json, os, time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(0)
torch.set_num_threads(os.cpu_count() or 4)
S = 28
D = 'data/quickdraw'
classes = json.load(open(f'{D}/classes.json'))

def load(split):
    x = np.fromfile(f'{D}/{split}.x.bin', dtype=np.uint8).reshape(-1, 1, S, S).astype(np.float32) / 255
    y = np.fromfile(f'{D}/{split}.y.bin', dtype=np.uint8).astype(np.int64)
    return torch.from_numpy(x), torch.from_numpy(y)

xtr, ytr = load('train')
xev, yev = load('eval')

class Net(nn.Module):
    def __init__(self, n):
        super().__init__()
        self.c1 = nn.Conv2d(1, 16, 3, padding=1)
        self.c2 = nn.Conv2d(16, 32, 3, padding=1)
        self.c3 = nn.Conv2d(32, 64, 3, padding=1)
        self.f1 = nn.Linear(64 * 3 * 3, 128)
        self.f2 = nn.Linear(128, n)
        self.drop = nn.Dropout(.3)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.c1(x)), 2)   # 14×14
        x = F.max_pool2d(F.relu(self.c2(x)), 2)   # 7×7
        x = F.max_pool2d(F.relu(self.c3(x)), 2)   # 3×3
        x = self.drop(F.relu(self.f1(x.flatten(1))))
        return self.f2(x)

net = Net(len(classes))
opt = torch.optim.Adam(net.parameters(), lr=2e-3)
EPOCHS = int(os.environ.get('EPOCHS', 8))
sched = torch.optim.lr_scheduler.OneCycleLR(opt, max_lr=3e-3, total_steps=EPOCHS * ((len(xtr) + 255) // 256))

def shift(x):
    # Small random translations: players rarely draw exactly centered strokes the same way.
    dx, dy = np.random.randint(-2, 3, size=2)
    return torch.roll(x, shifts=(int(dy), int(dx)), dims=(2, 3))

def evaluate():
    net.eval()
    with torch.no_grad():
        logits = net(xev)
        top1 = (logits.argmax(1) == yev).float().mean().item()
        top3 = (logits.topk(3, 1).indices == yev[:, None]).any(1).float().mean().item()
    net.train()
    return top1, top3

for epoch in range(EPOCHS):
    t0 = time.time()
    perm = torch.randperm(len(xtr))
    for i in range(0, len(xtr), 256):
        idx = perm[i:i + 256]
        loss = F.cross_entropy(net(shift(xtr[idx])), ytr[idx])
        opt.zero_grad(); loss.backward(); opt.step(); sched.step()
    top1, top3 = evaluate()
    print(f'epoch {epoch + 1}: loss {loss.item():.3f}  eval top1 {top1:.3f} top3 {top3:.3f}  ({time.time() - t0:.0f}s)', flush=True)

# Export: per-tensor symmetric int8. Conv weights stay in PyTorch's [out, in, kh, kw] layout.
net.eval()
layers = []
for name, p in net.state_dict().items():
    a = p.numpy().astype(np.float32)
    scale = float(np.abs(a).max() / 127) or 1.0
    q = np.clip(np.round(a / scale), -127, 127).astype(np.int8)
    layers.append({'name': name, 'shape': list(a.shape), 'scale': scale, 'data': base64.b64encode(q.tobytes()).decode()})

top1, top3 = evaluate()
with open('shared/sketch/model.gen.ts', 'w') as f:
    f.write('// Generated by ml/train.py. Do not edit. Trained on Quick, Draw! (Google, CC BY 4.0).\n')
    f.write(f'// Eval accuracy (float): top-1 {top1:.3f}, top-3 {top3:.3f} over {len(classes)} classes.\n')
    f.write('export const MODEL = ' + json.dumps({'classes': classes, 'size': S, 'layers': layers}) + ' as const\n')

with torch.no_grad():
    json.dump({'x': xev[:20].flatten(1).tolist(), 'logits': net(xev[:20]).tolist()}, open(f'{D}/parity.json', 'w'))
print('exported', sum(p.numel() for p in net.parameters()), 'params')
